# Generated by Django 2.1.2 on 2019-02-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElmaApp', '0003_auto_20190215_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(default='', max_length=20),
        ),
    ]
